models/Task.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "task".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $due_date
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
class Task extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'task';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'created_at'], 'required'],
            [['description'], 'string'],
            [['status'], 'integer'],
            [['created_at', 'updated_at', 'due_date'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'description' => Yii::t('app', 'Description'),
            'due_date' => Yii::t('app', 'Due date'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    public function beforeValidate() 
    {
        // New record
        if ($this->isNewRecord)
        {
            $this->created_at = date("Y-m-d H:i:s");
        }
        
        // Existing record
        else
        {
            $this->updated_at = date("Y-m-d H:i:s");
        }
        
        return parent::beforeValidate();
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use yii\web\Controller;

class SiteController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

}

controllers/TaskController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use app\models\Task;

class TaskController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'ajax-delete' => ['post'],
                    'ajax-set-status' => ['post']
                ],
            ],
        ];
    }
    
    // View tasks list
    public function actionIndex($sort = null)
    {
        switch($sort)
        {
            case 'incomplete':
                $query = Task::find()->where("status = 0");
                break;
            case 'complete':
                $query = Task::find()->where("status = 1");
                break;
            default:
                $query = Task::find();
                break;
        }
        
        $dataProvider   = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 25,
            ],
        ]);
        
        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    // View task
    public function actionView($id)
    {
        $model = $this->find($id);
        
        return $this->render('view', [
            'model' => $model
        ]);
    }

    // Create new task
    public function actionCreate()
    {
        $model = new Task();
        
        // Create logic
        if ($model->load(Yii::$app->request->post()) && $model->validate())
        {
            // Creating successful
            if ($model->save())
            {
                Yii::$app->session->setFlash('success', Yii::t('app', 'Task created!'));
                return $this->refresh();
            }
            
            // Creating failed
            else
            {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Something went wrong!'));
                return $this->refresh();
            }
        }
        
        return $this->render('create', [
            'model' => $model
        ]);
    }
    
    // Update existing task
    public function actionUpdate($id)
    {
        $model = $this->find($id);
        
        // Update logic
        if ($model->load(Yii::$app->request->post()) && $model->validate())
        {
            // Update successful
            if ($model->save())
            {
                Yii::$app->session->setFlash('success', Yii::t('app', 'Task updated!'));
                return $this->refresh();
            }
            
            // Update failed
            else
            {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Something went wrong!'));
                return $this->refresh();
            }
        }
        
        return $this->render('update', [
            'model' => $model
        ]);
    }
    
    // Ajax update task
    public function actionAjaxUpdate($id)
    {
        // Find existing model
        $model = $this->find($id);
        // Populate model with new values
        $model->load(Yii::$app->request->post());
        
        // Return update result as boolean
        return $model->save();
    }

    // Delete task (post request only)
    public function actionDelete($id)
    {
        // Find model to delete
        $model = $this->find($id);
        
        // Deletion success
        if ($model->delete())
        {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Task deleted!'));
            return $this->redirect(['index']);
        }
        
        // Deletion failed
        else
        {
            Yii::$app->session->setFlash('error', Yii::t('app', 'Task deletion failed!'));
            return $this->redirect(['index']);
        }
    }
    
    // Delete task via ajax request
    public function actionAjaxDelete($id)
    {
        // Find model to delete
        $model = $this->find($id);
        
        // Return deletion result (boolean)
        return $model->delete();
    }
    
    // Set task status via ajax request
    public function actionAjaxSetStatus($id, $status)
    {
        $model = $this->find($id);
        
        if ($status == '1' || $status == '0')
        {
            $model->status = $status;
            return $model->save();
        }
        
        else
        {
            return false;
        }
            
    }

    // Find task model via ar model
    private function find($id)
    {
        $model = Task::findOne($id);
        
        if ($model !== null) 
        {
            return $model;
        }
        else 
        {
            throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
        }
    }
}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>

    <div class="container">
        <div class="row message-area">
            <div class="col-lg-12">
                <?php if (Yii::$app->session->hasFlash('success')): ?>
                <div class="alert alert-success">
                    <?php echo Yii::$app->session->getFlash('success') ?>
                </div>

                <?php elseif (Yii::$app->session->hasFlash('error')): ?>
                <div class="alert alert-danger">
                    <?php echo Yii::$app->session->getFlash('error') ?>
                </div>
                <?php elseif (Yii::$app->session->hasFlash('info')): ?>
                <div class="alert alert-info">
                    <?php echo Yii::$app->session->getFlash('info') ?>
                </div>
                <?php endif; ?>
            </div>
        </div>
        
        <div class="row">
            <div class="col-lg-12">
                <?= $content ?>
            </div>
        </div>
    </div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/task/_form.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>

<?php 
$action = ($model->isNewRecord) ? '' : Yii::$app->urlManager->createUrl(['task/ajax-update', 'id' => $model->id]);
$form = ActiveForm::begin([
    'id' => 'task-form',
    'action' => $action,
    'method' => 'post'
]); 
?>

    <?= $form->field($model, 'title')->textInput() ?>
    <?= $form->field($model, 'description')->textarea() ?>
    <?= $form->field($model, 'due_date')->textInput() ?>
    <?=
    $form->field($model, 'status')->dropDownList([
        '0' => \Yii::t('app', 'Undone'),
        '1' => \Yii::t('app', 'Done')
    ]);
    ?>


    <div class="form-group clearfix">
        <?= 
        Html::submitButton(
            Yii::t('app', 'Save'), 
            [
                'class' => $model->isNewRecord ? 'btn btn-success save-btn' : 'btn btn-primary save-btn'
            ],
            [
                'class' => 'pull-left'
            ]
        ) 
        ?>
        
        <?php if (!$model->isNewRecord): ?>
        <?= 
        Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger pull-right',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) 
        ?>
        <?php endif; ?>
    </div>

<?php ActiveForm::end(); ?>

views/task/_header.php
<?php
use yii\helpers\Html;
?>

<header class="clearfix">
    <div class="pull-left">
        <?= Html::a(Yii::t('app', 'Add new task'), ['create'], ['class' => 'btn btn-success']) ?>
    </div>
    
    <div class="pull-right">
        <?= Html::a(Yii::t('app', 'Completed tasks'), ['index', 'sort' => 'complete'], ['class' => 'btn btn-default']) ?>
        <?= Html::a(Yii::t('app', 'Incomplete tasks'), ['index', 'sort' => 'incomplete'], ['class' => 'btn btn-default']) ?>
        <?= Html::a(Yii::t('app', 'All tasks'), ['index'], ['class' => 'btn btn-default']) ?>
    </div>
</header>

<hr />

views/task/create.php
<?php
$this->title = Yii::t('app', 'Add new task');
?>

<?= $this->render('_header'); ?>

<h2><?= $this->title ?></h2>
<?= $this->render('_form', ['model' => $model]); ?>

views/task/index.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;

$this->title = Yii::t('app', 'Tasks')
?>

<?= $this->render('_header'); ?>

<h2><?= $this->title ?></h2>
<?php \yii\widgets\Pjax::begin(); ?>
<?php
echo GridView::widget([
    'id' => 'task-list',
    'dataProvider'=> $dataProvider,
    'summary' => false,
    'columns' => [
        [
            'attribute' => false,
            'format' => 'raw',
            'value' => function ($model) 
            {                
                return 
                    Html::a(($model->status == 1) 
                            ? '<span class="glyphicon glyphicon-remove"></span>' 
                            : '<span class="glyphicon glyphicon-ok"></span>',
                        [
                            'ajax-set-status',
                            'id' => $model->id,
                            'status' => ($model->status == 1) ? 0 : 1
                        ],
                        [
                            'class' => 'set-status'
                        ]
                    );

            },
        ],
        'title',
        'due_date',
        [
            'attribute' => false,
            'format' => 'raw',
            'value' => function ($model) 
            {                
                return 
                    Html::a(Yii::t('app', 'View'),
                        [
                            'view',
                            'id' => $model->id,
                        ]
                    );

            },
        ],
        [
            'attribute' => false,
            'format' => 'raw',
            'value' => function ($model) 
            {                
                return 
                    Html::a(Yii::t('app', 'Delete'),
                        [
                            'ajax-delete',
                            'id' => $model->id,
                        ],
                        [
                            'class' => 'delete'
                        ]
                    );

            },
        ]
    ]
]);
?>
<?php \yii\widgets\Pjax::end(); ?>

<?php $this->registerJs(\Yii::$app->controller->renderPartial('js/index.js')); ?>

views/task/update.php
<?php
$this->title = Yii::t('app', 'Edit task');
?>

<?= $this->render('_header'); ?>

<h2><?= $this->title ?></h2>
<?= $this->render('_form', ['model' => $model]); ?>
<?php $this->registerJs(\Yii::$app->controller->renderPartial('js/update.js')); ?>

views/task/view.php
<?php
use yii\helpers\Html;

$this->title = Yii::t('app', 'Task')
?>

<?= $this->render('_header'); ?>

<h2><?= $this->title ?></h2>
<table class="table table-striped table-bordered">
    <tbody>
        <tr>
            <th><?= Yii::t('app', 'Title') ?></th>
            <td><?= Html::encode($model->title) ?></td>
        </tr>
        
        <tr>
            <th><?= Yii::t('app', 'Description') ?></th>
            <td><?= Html::encode($model->description) ?></td>
        </tr>
        
        <tr>
            <th><?= Yii::t('app', 'Due date') ?></th>
            <td><?= Html::encode($model->due_date) ?></td>
        </tr>
        
        <tr>
            <th><?= Yii::t('app', 'Status') ?></th>
            <td><?= ($model->status === 1) ? Yii::t('app', 'Done') : Yii::t('app', 'Undone') ?></td>
        </tr>
    </tbody>
</table>

<div class="clearfix">
    <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary pull-left']) ?>
    <?= 
    Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
        'class' => 'btn btn-danger pull-right',
        'data' => [
            'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
            'method' => 'post',
        ],
    ]) 
    ?>
</div>